name: Test PHP Tools on all supported PHP versions

on: [push]

jobs:
  build:
    name: Verify all tools are available for each PHP version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-image: [php:5.6-alpine, php:7.1-alpine, php:7.2-alpine, php:7.3-alpine, php:7.4-alpine, php:8.0-alpine, php:8.1-alpine, php:8.2-alpine]
        phpunit-version: ["./5.5/phpunit/Dockerfile"]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Test for PHP CodeSniffer in root dir
        run: docker build ./phpcs --build-arg PHP_IMAGE=${{ matrix.php-image }}
      - name: Test for PHP Mess Detector in root dir
        run: docker build ./phpmd --build-arg PHP_IMAGE=${{ matrix.php-image }}
      - name: Test for PHP PhpMetrics in root dir
        run: docker build ./phpmetrics --build-arg PHP_IMAGE=${{ matrix.php-image }}
      - name: Test for PHPUnit in root dir
        run: docker build ./phpunit --build-arg PHP_IMAGE=${{ matrix.php-image }}
      - name: Test for PHPStan in root dir
        run: docker build ./phpstan --build-arg PHP_IMAGE=${{ matrix.php-image }}
