name: Test PHP Tools on all supported PHP versions

on: [push]

jobs:
  build:
    name: Verify all tools are available for each PHP version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-image: ['5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Test for PHP CodeSniffer in root dir
        run: docker build ./${{ matrix.php-image }}/phpcs
      - name: Test for PHP Mess Detector in root dir
        run: docker build ./${{ matrix.php-image }}/phpmd
      - name: Test for PHP PhpMetrics in root dir
        run: docker build ./${{ matrix.php-image }}/phpmetrics
      - name: Test for PHPUnit in root dir
        run: docker build ./${{ matrix.php-image }}/phpunit
      - name: Test for PHPStan in root dir
        run: docker build ./${{ matrix.php-image }}/phpstan
